# Add your additional Hyprland configurations here
#
# This is an additional key binding
# bind = $mainMod CTRL, up, workspace, empty
#
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }

# Blur for waybar
#layerrule = blur, waybar

# input method config
# env = XMODIFIERS,@im=fcitx
# env = QT_IM_MODULE,fcitx
# env = GTK_IM_MODULE,fcitx
# env = SDL_IM_MODULE,fcitx
# env = GLFW_IM_MODULE,fcitx
# env = IMSETTINGS_MODULE,fcitx
# env = INPUT_METHOD,fcitx

exec-once = fcitx5 -d
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# language
env = LANG=zh_CN.UTF-8
env = LANGUAGE=zh_CN:en_US
